### ISSUE TITLE
Mac M1 Support

### ISSUE THREAD

**Issue by DenisStetsenko** [steve228uk/YouTube-Music#147]
Do you guys know any info about Mac M1 support for this app?

**Comment by arigato-one** [comment]
I am using it on a Mac M1, works great.

**Comment by DenisStetsenko** [comment]
> But what the author is asking here is there a version of the app designed for M1 rather than Intel.

- Exactly :) As we all know there is a HUGE difference between native arm64(M1) support and Rosetta emulation. 
There are some big players on the market that still didn't provide such support (e.x. Logitech), so obviously having YT music with native M1 support would be amazing if no more.

**Comment by TimOliver** [comment]
Hey folks! Yep, this thing is on my radar. The reason why the app didn't have M1 support from the start was that since we're producing builds with GitHub Actions, which was stuck on macOS 10.15 for a bit longer than expected, it wasn't possible to produce M1 builds with it.

And now that GitHub Actions has finally moved to Big Sur, the dependencies of the build script have changed and it's stopped working. Ahh software. 🤣

I'll set aside some time to fix the build script and hopefully that's all that's needed to enable Universal builds now. Thanks!

**Comment by davaeron** [comment]
Got 1.2.0 version from Github. Same experience as Chris. Overall works well + app asks for Accessibility rights that it didn't ask on version from website.
Thank you for M1 version.

**Comment by TimOliver** [comment]
Cool thanks guys! Good to hear it's working properly on M1 hardware. I've got an M1 Max MacBook Pro coming in the mail soon. I can't wait!

Yeah, I don't have access to the website, so I can't upload new builds there. I'll have to ask Steve about that.

Right. The accessibility request is from another PR that was filed to try and globally hook the media control keys when the app is active to enable forward and back support. There's an issue with this app still where the internal web view hooks control of the video player, but it's not smart enough to know what the next song is.

It _seems_ like maybe the behaviour has become better in Monterey, so maybe we don't need to rely on that media hooking library anymore, but we'd need to test it.

In any case, enjoy!
