### ISSUE TITLE
Wrong cover image in notification

### ISSUE THREAD

**Issue by Regaddi** [steve228uk/YouTube-Music#56]
When the notification pops up with the new song title, artist and cover image the cover image is not correct.
It seems to have cached one that I listened to previously.

In this example:
Playing Amy Macdonald - Never Too late
The image relates to Gasmac Gilmore - Dead Donkey

<img width="343" alt="Bildschirmfoto 2019-04-04 um 13 16 48" src="https://user-images.githubusercontent.com/1336590/55551785-ec12ea80-56db-11e9-82e7-77e2413dc31f.png">

**Comment by Slistersoft** [comment]
I'm going to take a stab at fixing this. This is the first time I have tried any Mac app development though so don't hold your breath lol.

**Comment by wonsuc** [comment]
I experienced the same issue before.

**Comment by 4ndv** [comment]
For me it shows image of the playlist instead of song album art:

Notification:
![изображение](https://user-images.githubusercontent.com/10115449/69703058-2590de00-1123-11ea-8e77-9c1e6b332d64.png)

Song:
![изображение](https://user-images.githubusercontent.com/10115449/69703093-40635280-1123-11ea-998a-95598e212a80.png)

Playlist image:
![изображение](https://user-images.githubusercontent.com/10115449/69703113-4b1de780-1123-11ea-900d-e46e8184ab2f.png)

**Comment by jscheel** [comment]
I've attached a PR that fixes this.
